export const RAFFLES = [
    {
        id: "1",
        title: "Sorteo de Smartphone Pro",
        description: "Participa en nuestra rifa exclusiva y podrías ser el afortunado ganador de un Smartphone Pro de última generación. Con su pantalla OLED de 6.7 pulgadas, sistema de cámaras de nivel profesional y batería de larga duración, este dispositivo redefine lo que es posible en un móvil.",
        price: 5.00,
        totalTickets: 1000,
        soldTickets: 750,
        imageUrl: "/images/hero.png",
        endDate: "2024-12-31T23:59:59",
        images: ["/images/hero.png", "/images/raffle-detail.png"],
    },
    {
        id: "2",
        title: "Gana la Consola Next-Gen",
        description: "Lleva tu experiencia de juego al siguiente nivel con la consola más potente del mercado. Gráficos 4K, tiempos de carga ultrarrápidos y un catálogo de juegos increíble te esperan.",
        price: 10.00,
        totalTickets: 500,
        soldTickets: 450,
        imageUrl: "/images/raffle-detail.png",
        endDate: "2024-12-30T23:59:59",
        images: ["/images/raffle-detail.png", "/images/hero.png"],
    },
    {
        id: "3",
        title: "Kit de Viaje de Lujo",
        description: "Todo lo que necesitas para tu próxima aventura. Incluye maleta de alta gama, almohada de viaje ergonómica, auriculares con cancelación de ruido y más accesorios premium.",
        price: 7.50,
        totalTickets: 800,
        soldTickets: 300,
        imageUrl: "/images/raffle-detail.png",
        endDate: "2025-01-15T23:59:59",
        images: ["/images/raffle-detail.png", "/images/hero.png"],
    },
]
